# Generated by Django 4.2.7 on 2024-04-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='userview',
        ),
    ]
