# Generated by Django 4.2.7 on 2024-04-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_user_review_userview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='userview',
            new_name='user',
        ),
    ]
