# Generated by Django 4.2.7 on 2024-05-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_shippingaddress_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_product',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
