# Generated by Django 4.2.7 on 2024-05-18 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
    ]
