# Generated by Django 4.2.7 on 2024-05-18 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_remove_shippingaddress_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='id_man',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.shippingaddress'),
        ),
    ]
