# Generated by Django 4.2.7 on 2024-05-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_order_id_man'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item_product',
        ),
        migrations.AddField(
            model_name='order',
            name='all_product',
            field=models.ManyToManyField(blank=True, null=True, to='app.product'),
        ),
    ]
