# Generated by Django 4.2.7 on 2024-05-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_order_item_product_order_all_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='totall',
        ),
    ]
