# Generated by Django 4.2.7 on 2024-06-04 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_rename_total_order_totall'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='all_product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id_man',
        ),
        migrations.RemoveField(
            model_name='order',
            name='totall',
        ),
    ]
