# Generated by Django 4.2.7 on 2024-06-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_item_review_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='item',
        ),
    ]
